In [1]:
# 2.1 Loading Necessary Libraries
import numpy as np  # linear algebra
import pandas as pd  # data processing
import matplotlib.pyplot as plt  # For basic data visualization.
import seaborn as sns  # For statistical data visualization
import warnings  # To manage warnings

# Suppressing FutureWarning
warnings.filterwarnings("ignore")

# 2.2 Loading Dataets
train_df = pd.read_csv("../data/spaceship-titanic/train.csv")
test_df = pd.read_csv("../data/spaceship-titanic/test.csv")

# Let's quickly check the data by viewing the first few rows.
print(train_df.head())
print(test_df.head())

  PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines

   Transported
0        False
1         True
2        False
3        False
4         True
  PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [24]:
y_train = train_df["Transported"]
train_len = len(train_df)

X_train_temp = train_df.drop(columns=["Transported"])

all_data = pd.concat([X_train_temp, test_df], axis=0).reset_index(drop=True)


def missing_data_table(df):
    total = (
        df.isnull().sum().sort_values(ascending=False)
    )  # Total missing values in each column.
    percent = (df.isnull().sum() / df.isnull().count()).sort_values(
        ascending=False
    )  # Percentage of missing values.

    missing_data = pd.concat(
        [total, percent], axis=1, keys=["Total", "Percent"]
    )  # Combine the results.

    # Filter columns that actually have missing values.
    return missing_data[missing_data["Total"] > 0]


# Display missing data for the training dataset.
missing_data = missing_data_table(all_data)
missing_data

              Total   Percent
CryoSleep       310  0.023901
ShoppingMall    306  0.023593
Cabin           299  0.023053
VIP             296  0.022822
Name            294  0.022668
FoodCourt       289  0.022282
HomePlanet      288  0.022205
Spa             284  0.021897
Destination     274  0.021126
Age             270  0.020817
VRDeck          268  0.020663
RoomService     263  0.020278

In [25]:
all_data["CryoSleep"] = all_data["CryoSleep"].fillna("Unknown")
all_data["HomePlanet"] = all_data["HomePlanet"].fillna("Unknown")
all_data["Destination"] = all_data["Destination"].fillna("Unknown")

all_data["ShoppingMall"] = all_data["ShoppingMall"].fillna(
    all_data["ShoppingMall"].median()
)
all_data["FoodCourt"] = all_data["FoodCourt"].fillna(all_data["FoodCourt"].median())
all_data["Spa"] = all_data["Spa"].fillna(all_data["Spa"].median())
all_data["VRDeck"] = all_data["VRDeck"].fillna(all_data["VRDeck"].median())
all_data["RoomService"] = all_data["RoomService"].fillna(
    all_data["RoomService"].median()
)

all_data["total_spending"] = all_data[
    ["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]
].sum(axis=1)

all_data["Age"] = all_data["Age"].fillna(all_data["Age"].median())

all_data["CabinDeck"] = all_data["Cabin"].str.split("/").str[0]
all_data["CabinNum"] = all_data["Cabin"].str.split("/").str[1]
all_data["CabinSide"] = all_data["Cabin"].str.split("/").str[2]

all_data["CabinDeck"] = all_data["CabinDeck"].fillna("Unknown")
all_data["CabinNum"] = all_data["CabinNum"].fillna("Unknown")
all_data["CabinSide"] = all_data["CabinSide"].fillna("Unknown")

all_data["VIP"] = all_data["VIP"].apply(lambda x: 1 if x is True else 0)

all_data["last_name"] = all_data["Name"].str.split(" ").str[1]

all_data["last_name"] = all_data["last_name"].fillna("Unknown")

all_data = all_data.drop(columns=["Cabin", "Name"])

In [26]:
missing_data = missing_data_table(all_data)
missing_data

Empty DataFrame
Columns: [Total, Percent]
Index: []

In [27]:
all_data["PassengerGroup"] = all_data["PassengerId"].str.split("_").str[0]

all_data["PassengerGroup_size"] = all_data.groupby("PassengerGroup")[
    "PassengerGroup"
].transform("count")


def categorize_group(size):
    if size == 1:
        return "Solo"
    elif size <= 4:
        return "Small_Group"
    else:
        return "Large_Group"


all_data["PassengerGroup_type"] = all_data["PassengerGroup_size"].apply(
    categorize_group
)

all_data["family_size"] = all_data.groupby(["PassengerGroup", "last_name"])[
    "PassengerId"
].transform("count")

In [28]:
missing_data = missing_data_table(all_data)
missing_data

Empty DataFrame
Columns: [Total, Percent]
Index: []

In [29]:
all_data = all_data.drop(
    columns=[
        "PassengerId",
        "RoomService",
        "FoodCourt",
        "ShoppingMall",
        "Spa",
        "VRDeck",
        "PassengerGroup_size",
    ],
    errors="ignore",
)

X_train = all_data.iloc[:train_len, :]
X_test = all_data.iloc[train_len:, :]

In [30]:
from sklearn.model_selection import KFold, cross_val_score
import numpy as np


def log_loss_cv(model, X, y):
    kf = KFold(n_splits=10, shuffle=True, random_state=42)

    # REMOVE .values here! Pass the DataFrame 'X' directly.
    neg_log_losses = cross_val_score(model, X, y, scoring="neg_log_loss", cv=kf)

    return -neg_log_losses

In [31]:
X_train

,HomePlanet,CryoSleep,Destination,Age,VIP,total_spending,CabinDeck,CabinNum,CabinSide,last_name,PassengerGroup,PassengerGroup_type,family_size
0,Europa,False,TRAPPIST-1e,39.0,0,0.0,B,0,P,Ofracculy,0001,Solo,1
1,Earth,False,TRAPPIST-1e,24.0,0,736.0,F,0,S,Vines,0002,Solo,1
2,Europa,False,TRAPPIST-1e,58.0,1,10383.0,A,0,S,Susent,0003,Small_Group,2
3,Europa,False,TRAPPIST-1e,33.0,0,5176.0,A,0,S,Susent,0003,Small_Group,2
4,Earth,False,TRAPPIST-1e,16.0,0,1091.0,F,1,S,Santantines,0004,Solo,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,55 Cancri e,41.0,1,8536.0,A,98,P,Noxnuther,9276,Solo,1
8689,Earth,True,PSO J318.5-22,18.0,0,0.0,G,1499,S,Mondalley,9278,Solo,1
8690,Earth,False,TRAPPIST-1e,26.0,0,1873.0,G,1500,S,Connon,9279,Solo,1
8691,Europa,False,55 Cancri e,32.0,0,4637.0,E,608,S,Hontichre,9280,Small_Group,2
8692,Europa,False,TRAPPIST-1e,44.0,0,4826.0,E,608,S,Hontichre,9280,Small_Group,2

In [32]:
missing_data = missing_data_table(X_train)
missing_data

Empty DataFrame
Columns: [Total, Percent]
Index: []

In [33]:
from catboost import CatBoostClassifier

cat_feature_indices = [
    "HomePlanet",
    "CryoSleep",
    "Destination",
    "VIP",
    "CabinDeck",
    "CabinNum",
    "CabinSide",
    "last_name",
    "PassengerGroup",
    "PassengerGroup_type",
]

params = {
    # --- Core Configuration ---
    "loss_function": "Logloss",  # Standard for binary classification
    "eval_metric": "Accuracy",  # Useful to monitor during training
    "task_type": "GPU",  # Uses NVIDIA GPU for speed
    "random_seed": 42,  # For reproducibility
    # --- Training Speed & Depth ---
    "iterations": 2000,  # Number of trees
    "learning_rate": 0.02,  # Step size (lower = more robust)
    "depth": 6,  # Tree depth (6 is usually the 'sweet spot')
    "early_stopping_rounds": 50,  # Stop if no improvement
    # --- Overfitting Protection (Regularization) ---
    "l2_leaf_reg": 10,  # Penalty for leaf complexity
    "random_strength": 2,  # Randomness in split scoring
    "min_data_in_leaf": 15,  # Min samples per leaf
    "bagging_temperature": 1,  # Randomness of the bootstrap
    # --- Categorical Feature Handling ---
    "one_hot_max_size": 10,  # Categories with > 10 unique values get Target Encoded
    "model_size_reg": 0.5,  # Prevents high-cardinality features from bloating model size
    "max_ctr_complexity": 2,  # Limits the complexity of combining categorical features
    # --- GPU Specific Performance ---
    "gpu_ram_part": 0.9,  # Reserve 90% of GPU memory
    "bootstrap_type": "Bayesian",  # Required for bagging_temperature on GPU
    # --- Logging & Verbosity ---
    "verbose": 200,  # Print progress every 200 steps
    "allow_writing_files": False,  # Keeps your directory clean
}

model = CatBoostClassifier(**params, cat_features=cat_feature_indices)

catboost_rmse = log_loss_cv(model, X_train, y_train)

0:	learn: 0.7408922	total: 65.2ms	remaining: 2m 10s
200:	learn: 0.7527803	total: 10.3s	remaining: 1m 32s
400:	learn: 0.7585325	total: 20.3s	remaining: 1m 20s
600:	learn: 0.7636457	total: 29.9s	remaining: 1m 9s
800:	learn: 0.7676083	total: 39.1s	remaining: 58.5s
1000:	learn: 0.7705484	total: 48.8s	remaining: 48.7s
1200:	learn: 0.7736163	total: 58.3s	remaining: 38.8s
1400:	learn: 0.7764285	total: 1m 7s	remaining: 28.9s
1600:	learn: 0.7782181	total: 1m 17s	remaining: 19.3s
1800:	learn: 0.7796242	total: 1m 26s	remaining: 9.59s
1999:	learn: 0.7814138	total: 1m 37s	remaining: 0us
0:	learn: 0.7411479	total: 60.1ms	remaining: 2m
200:	learn: 0.7509907	total: 11.6s	remaining: 1m 44s
400:	learn: 0.7562316	total: 23.1s	remaining: 1m 32s
600:	learn: 0.7608334	total: 33.8s	remaining: 1m 18s
800:	learn: 0.7617282	total: 44s	remaining: 1m 5s
1000:	learn: 0.7647961	total: 54.4s	remaining: 54.3s
1200:	learn: 0.7672248	total: 1m 4s	remaining: 43s
1400:	learn: 0.7690144	total: 1m 14s	remaining: 32s
1600:	learn: 0.7709319	total: 1m 25s	remaining: 21.2s
1800:	learn: 0.7734884	total: 1m 34s	remaining: 10.4s
1999:	learn: 0.7747667	total: 1m 44s	remaining: 0us
0:	learn: 0.7422984	total: 72.4ms	remaining: 2m 24s
200:	learn: 0.7492011	total: 11.3s	remaining: 1m 41s
400:	learn: 0.7577656	total: 22.5s	remaining: 1m 29s
600:	learn: 0.7632622	total: 33.2s	remaining: 1m 17s
800:	learn: 0.7655631	total: 43.4s	remaining: 1m 4s
1000:	learn: 0.7667135	total: 53.6s	remaining: 53.5s
1200:	learn: 0.7685031	total: 1m 3s	remaining: 42.1s
1400:	learn: 0.7706762	total: 1m 13s	remaining: 31.3s
1600:	learn: 0.7706762	total: 1m 22s	remaining: 20.5s
1800:	learn: 0.7715710	total: 1m 31s	remaining: 10.1s
1999:	learn: 0.7718267	total: 1m 40s	remaining: 0us
0:	learn: 0.7428425	total: 55.1ms	remaining: 1m 50s
200:	learn: 0.7506391	total: 10.3s	remaining: 1m 32s
400:	learn: 0.7558793	total: 20.8s	remaining: 1m 23s
600:	learn: 0.7627812	total: 30.9s	remaining: 1m 12s
800:	learn: 0.7658487	total: 41.2s	remaining: 1m 1s
1000:	learn: 0.7686605	total: 51.2s	remaining: 51.1s
1200:	learn: 0.7722393	total: 1m 1s	remaining: 41s
1400:	learn: 0.7737730	total: 1m 11s	remaining: 30.7s
1600:	learn: 0.7763292	total: 1m 21s	remaining: 20.4s
1800:	learn: 0.7778630	total: 1m 31s	remaining: 10.1s
1999:	learn: 0.7793967	total: 1m 42s	remaining: 0us
0:	learn: 0.7433538	total: 55.3ms	remaining: 1m 50s
200:	learn: 0.7535787	total: 10.9s	remaining: 1m 37s
400:	learn: 0.7590746	total: 21s	remaining: 1m 23s
600:	learn: 0.7641871	total: 31.3s	remaining: 1m 12s
800:	learn: 0.7681493	total: 41.7s	remaining: 1m 2s
1000:	learn: 0.7714724	total: 51.9s	remaining: 51.8s
1200:	learn: 0.7732618	total: 1m 1s	remaining: 41.2s
1400:	learn: 0.7767127	total: 1m 11s	remaining: 30.6s
1600:	learn: 0.7773517	total: 1m 21s	remaining: 20.3s
1800:	learn: 0.7792689	total: 1m 31s	remaining: 10.1s
1999:	learn: 0.7806748	total: 1m 41s	remaining: 0us
0:	learn: 0.7388804	total: 52.2ms	remaining: 1m 44s
200:	learn: 0.7498722	total: 11.2s	remaining: 1m 40s
400:	learn: 0.7552403	total: 22.6s	remaining: 1m 29s
600:	learn: 0.7597137	total: 33.6s	remaining: 1m 18s
800:	learn: 0.7653374	total: 46.4s	remaining: 1m 9s
1000:	learn: 0.7691718	total: 59s	remaining: 58.9s
1200:	learn: 0.7721115	total: 1m 11s	remaining: 47.6s
1400:	learn: 0.7749233	total: 1m 24s	remaining: 36s
1600:	learn: 0.7767127	total: 1m 36s	remaining: 24s
1800:	learn: 0.7781186	total: 1m 48s	remaining: 12s
1999:	learn: 0.7800358	total: 1m 58s	remaining: 0us
0:	learn: 0.7428425	total: 54.4ms	remaining: 1m 48s
200:	learn: 0.7503834	total: 10.3s	remaining: 1m 32s
400:	learn: 0.7554959	total: 20.5s	remaining: 1m 21s
600:	learn: 0.7616309	total: 30.2s	remaining: 1m 10s
800:	learn: 0.7664877	total: 40.4s	remaining: 1m
1000:	learn: 0.7682771	total: 51.7s	remaining: 51.6s
1200:	learn: 0.7700665	total: 1m 4s	remaining: 42.6s
1400:	learn: 0.7727505	total: 1m 15s	remaining: 32.4s
1600:	learn: 0.7758180	total: 1m 27s	remaining: 21.9s
1800:	learn: 0.7783742	total: 1m 39s	remaining: 10.9s
1999:	learn: 0.7799080	total: 1m 49s	remaining: 0us
0:	learn: 0.7399029	total: 98.6ms	remaining: 3m 17s
200:	learn: 0.7462935	total: 12s	remaining: 1m 47s
400:	learn: 0.7525562	total: 23.6s	remaining: 1m 34s
600:	learn: 0.7584356	total: 35.3s	remaining: 1m 22s
800:	learn: 0.7618865	total: 46.5s	remaining: 1m 9s
1000:	learn: 0.7648262	total: 58s	remaining: 57.9s
1200:	learn: 0.7675102	total: 1m 8s	remaining: 45.6s
1400:	learn: 0.7696830	total: 1m 17s	remaining: 33.2s
1600:	learn: 0.7705777	total: 1m 28s	remaining: 22.1s
1800:	learn: 0.7724949	total: 1m 38s	remaining: 10.9s
1999:	learn: 0.7728783	total: 1m 48s	remaining: 0us
0:	learn: 0.7413088	total: 53.5ms	remaining: 1m 46s
200:	learn: 0.7500000	total: 11s	remaining: 1m 38s
400:	learn: 0.7597137	total: 21.6s	remaining: 1m 25s
600:	learn: 0.7650818	total: 33.1s	remaining: 1m 17s
800:	learn: 0.7680215	total: 43.7s	remaining: 1m 5s
1000:	learn: 0.7713446	total: 53.4s	remaining: 53.3s
1200:	learn: 0.7739008	total: 1m 3s	remaining: 41.9s
1400:	learn: 0.7774796	total: 1m 12s	remaining: 30.9s
1600:	learn: 0.7788855	total: 1m 21s	remaining: 20.4s
1800:	learn: 0.7822086	total: 1m 31s	remaining: 10.1s
1999:	learn: 0.7832311	total: 1m 40s	remaining: 0us
0:	learn: 0.7340235	total: 36.8ms	remaining: 1m 13s
200:	learn: 0.7451431	total: 9.89s	remaining: 1m 28s
400:	learn: 0.7502556	total: 19.7s	remaining: 1m 18s
600:	learn: 0.7543456	total: 29s	remaining: 1m 7s
800:	learn: 0.7597137	total: 38.1s	remaining: 57s
1000:	learn: 0.7616309	total: 47.5s	remaining: 47.4s
1200:	learn: 0.7639315	total: 57.4s	remaining: 38.2s
1400:	learn: 0.7671268	total: 1m 7s	remaining: 29s
1600:	learn: 0.7696830	total: 1m 19s	remaining: 19.7s
1800:	learn: 0.7710890	total: 1m 30s	remaining: 9.96s
1999:	learn: 0.7727505	total: 1m 39s	remaining: 0us

In [ ]:
print(f"CatBoost RMSE (Cross-Validation Mean): {catboost_rmse.mean():.4f}") 
print(f"CatBoost RMSE (Standard Deviation): {catboost_rmse.std():.4f}")

CatBoost RMSE (Cross-Validation Mean): 0.4960
CatBoost RMSE (Standard Deviation): 0.0157

In [35]:
model = CatBoostClassifier(**params, cat_features=cat_feature_indices)

model.fit(X_train, y_train)

0:	learn: 0.7400207	total: 45.6ms	remaining: 1m 31s
200:	learn: 0.7477281	total: 10.7s	remaining: 1m 35s
400:	learn: 0.7560106	total: 20.4s	remaining: 1m 21s
600:	learn: 0.7619924	total: 30.5s	remaining: 1m 11s
800:	learn: 0.7641781	total: 40.5s	remaining: 1m
1000:	learn: 0.7661337	total: 49.8s	remaining: 49.7s
1200:	learn: 0.7683193	total: 59.7s	remaining: 39.7s
1400:	learn: 0.7695847	total: 1m 9s	remaining: 29.7s
1600:	learn: 0.7711952	total: 1m 19s	remaining: 19.7s
1800:	learn: 0.7728057	total: 1m 28s	remaining: 9.8s
1999:	learn: 0.7740711	total: 1m 37s	remaining: 0us

In [37]:
id_col = test_df["PassengerId"]

def export_submission(model, id_col):
    preds = model.predict(X_test)

    submission = pd.DataFrame({"PassengerId": id_col, "Transported": preds})

    model_name = type(model).__name__
    submission.to_csv(f"{model_name}_submission.csv", index=False)


export_submission(model, id_col)